### ISSUE TITLE
1.0.5 dependencies not working

### ISSUE THREAD

**Issue by Mewel** [rafaskb/typing-label#10]
Putting the new 1.0.5 version into gradle the project is not building for me.

"Failed to resolve: com.github.rafaskb:typing-label:1.0.5"

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
        maven { url "https://jitpack.io" }
    }

    project(":core") {
      apply plugin: "java"

      dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
        compile "com.github.rafaskb:typing-label:1.0.5"
      }
    }

**Comment by rafaskb** [comment]
Thanks for the report! It seems like Jitpack doesn't handle releases very well, using `master` as the version works just fine. However we want proper releases, not just snapshots, so I returned to Maven Central like the way it was before.

It will take a few minutes or hours for the new version to be available on Maven Central, and once it is I'll update the README file with the correct instructions.

**Comment by rafaskb** [comment]
And done, we're back on Maven Central. README was updated with proper instructions on how to get TypingLabel version 1.0.5.

**Comment by Mewel** [comment]
Hm still not building and I dont see it on maven central: https://search.maven.org/search?q=com.rafaskoberg.gdx
Does it take so long to deploy?

**Comment by rafaskb** [comment]
Sorry about that, it was a mistake on my end. 1.0.5 should be working normally now, and also visible on Maven Central.
