### ISSUE TITLE
[question] clickable/touchable label

### ISSUE THREAD

**Issue by Mewel** [rafaskb/typing-label#11]
Is it possible to create a label which includes an external link. Kind of a text which is clickable? Could'nt find anything in the documention. Is this supported? Thanks!

**Comment by rafaskb** [comment]
Hey, clickable links are a bit out of the scope of this library, and it would be strange to have a link typing itself while being clickable I think.

However, it's not too hard to implement that feature, all you need is to detect mouse events, change the color of the label, change the cursor and draw an underline. VisUI does that very well:

[VisUI Web Demo](https://vis.kotcrab.com/demo/ui/)

[VisUI LinkLabel.java](https://github.com/kotcrab/vis-ui/blob/master/ui/src/main/java/com/kotcrab/vis/ui/widget/LinkLabel.java
)
