### ISSUE TITLE
Restart label in Listener

### ISSUE THREAD

**Issue by DranikProgrammer** [rafaskb/typing-label#2]
Hello!
Recently I noticed this : when I restart the label in the listener it just clears the text and doesn't show anything, but if I restart  it from the render method it works ....

`

		stage = new Stage();
		skin = new Skin(Gdx.files.internal("expee-ui.json"));

		TypingConfig.DEFAULT_CLEAR_COLOR = Color.BLACK;

		typingLabel = new TypingLabel("-", skin);
		stage.addActor(typingLabel);
		typingLabel.setPosition(300,300);

		typingLabel.setTypingListener(new TypingListener() {
			@Override
			public void event(String event) {

			}

			@Override
			public void end() {
				typingLabel.restart("{CLEARCOLOR} HELLO GUYS I AM RESTARTED");

			}
		});

		typingLabel.setText("{CLEARCOLOR} HELLO WORLD");

`

**Comment by rafaskb** [comment]
Silly mistake from my part, this should do the job. Thanks for the report.
