### ISSUE TITLE
Parent alpha not working

### ISSUE THREAD

**Issue by fgnm** [rafaskb/typing-label#28]
If the typing label is placed inside a scene2d group that fades (change alpha value) the label doesn't change alpha accordingly. The alpha works only if the text is wrapped between `{GRADIENT}` or `{RAINBOW}` but simple colors don't change alpha anymore.

This is a screen of a group with several buttons and labels with 0.4 alpha value
![image](https://user-images.githubusercontent.com/5543339/176227070-739038e1-5b39-481f-a671-46cca28fc90d.png)

Labels and buttons correctly apply parent alpha, while the typing label only works on the Treasures word which is wrapped into a `{GRADIENT}` tag

**Comment by rafaskb** [comment]
Huh that's odd, on my end changing the alpha of parents properly propagates it to all glyphs, even the ones without any tokens.
![image](https://user-images.githubusercontent.com/2331058/176780348-12f9aa90-1649-428a-b14c-2beee0847ada.png)

There was a big change regarding how colors are applied to glyphs in the latest update, which is only compatible with libGDX 1.11.0 (see https://github.com/rafaskb/typing-label/releases/tag/1.3.0). Can you please double check which TypingLabel and libGDX versions you're using?

**Comment by fgnm** [comment]
Yes, I'm sure to be on latest versions both of typing labels and libGDX.. I tried to switch to `textratypist` which has a 1:1 implementation of this library and the bug was fixed there.

**Comment by rafaskb** [comment]
> Yes, I'm sure to be on latest versions both of typing labels and libGDX.. I tried to switch to `textratypist` which has a 1:1 implementation of this library and the bug was fixed there.

Would you be able to provide some code containing the issue? I can't seem to reproduce it on my end.

**Comment by tommyettinger** [comment]
> Yes, I'm sure to be on latest versions both of typing labels and libGDX.. I tried to switch to `textratypist` which has a 1:1 implementation of this library and the bug was fixed there.

Woohoo! I'm 1:1! (I think.) If I remember this correctly, the typing-label code I initially copied into TextraTypist didn't fully handle parentAlpha from scene2d, but by sufficiently messing with the Batch color, it did get working without a ton of effort. Any fixes I had are unlikely to directly apply to typing-label, though, because of how differently the libraries store color internally...

**Comment by EtK2000** [comment]
Can confirm that I am experiencing this as well.
The code below is loosely based off my use case:
```java
class MyWindow extends VisWindow {
    private final VisTable textArea = new VisTable();
    private final VisScrollPane progressConversationScrollPane = new VisScrollPane(textArea);

    public MyWindow() {
        super("");
        progressConversationScrollPane.setFadeScrollBars(false);
        add(progressConversationScrollPane).growX().expandY().left().top().pad(5);
    }

    public void addLine(String text) {
        TypingLabel currentLine = new TypingLabel("{SLOWER}" + text, VisUI.getSkin());
        currentLine.parseTokens();
        currentLine.setTypingListener(listener);
        currentLine.setWrap(true);
        textArea.add(currentLine).growX().left().padBottom(5).padTop(5).row();
    }

    public void fadeOut() {
        clearActions();
        addAction(Actions.fadeOut(VisWindow.FADE_TIME, Interpolation.fade));
    }
}
```

**Comment by tommyettinger** [comment]
![java_owrFqKqy0R](https://github.com/rafaskb/typing-label/assets/160684/601a42cb-a50f-4541-b3d3-bfc58d5dda98)
If the default tokens don't include FADE or other changes to color, then parent alpha isn't respected by any text without a color set. This should help track down the culprit, so I'll take a look too.

**Comment by tommyettinger** [comment]
That was easy!
![java_tnPDOtzDZB](https://github.com/rafaskb/typing-label/assets/160684/b3c2ad26-4df4-43c0-a627-9db789941e59)
I opened a PR, #31 .
